// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmrSQSvxfj4EUhmzzO5v3VhpkVIFgbHes',
    appId: '1:584722890120:web:b39084ae1a75418e0e8e3d',
    messagingSenderId: '584722890120',
    projectId: 'bdfruteria',
    authDomain: 'bdfruteria.firebaseapp.com',
    storageBucket: 'bdfruteria.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS4WJHZWoemkDubn8DjtuAiSNjWi10vjI',
    appId: '1:584722890120:android:47a2ced2ac7c1e9c0e8e3d',
    messagingSenderId: '584722890120',
    projectId: 'bdfruteria',
    storageBucket: 'bdfruteria.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVLDyZjPZ3iw-zrEQ8TegaNfb1e6xj5cU',
    appId: '1:584722890120:ios:4bd013367a8746280e8e3d',
    messagingSenderId: '584722890120',
    projectId: 'bdfruteria',
    storageBucket: 'bdfruteria.firebasestorage.app',
    iosBundleId: 'com.example.dbfruteria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVLDyZjPZ3iw-zrEQ8TegaNfb1e6xj5cU',
    appId: '1:584722890120:ios:4bd013367a8746280e8e3d',
    messagingSenderId: '584722890120',
    projectId: 'bdfruteria',
    storageBucket: 'bdfruteria.firebasestorage.app',
    iosBundleId: 'com.example.dbfruteria',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmrSQSvxfj4EUhmzzO5v3VhpkVIFgbHes',
    appId: '1:584722890120:web:cba58ff6ecfc43970e8e3d',
    messagingSenderId: '584722890120',
    projectId: 'bdfruteria',
    authDomain: 'bdfruteria.firebaseapp.com',
    storageBucket: 'bdfruteria.firebasestorage.app',
  );
}
